[project]
name = "ruff-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veaceslavcalestru@gmail.com", email = "veaceslavcalestru@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ruff-tutorial = "ruff_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "ruff>=0.16.1",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "F",   # pyflakes (bugs)
    "E",   # pycodestyle (style errors)
    "I",   # isort (import sorting!)
    "B",   # bugbear (likely bugs & gotchas)
    "UP",  # pyupgrade (modernize old syntax)
    "PD",
    "NPY"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["E501"]
