# Устанавливаем максимально допустимую длину строки —
# 88 символов, как это делает форматтер black (удобно для split-view и терминала)
line-length = 88

# Указываем целевую версию Python — важно для правильной работы ренеймера, парсера и проверки синтаксиса
target-version = "py311"

[lint]
# Выбираем набор правил для анализа кода:
# E — ошибки стиля (pycodestyle)
# F — ошибки, связанные с переменными, импортами и т. д. (pyflakes)
# I — сортировка импортов (аналог isort)
# B — best practices из flake8-bugbear
select = ["E", "F", "I", "B"]

# Разрешаем автоисправление соответствующих ошибок
fixable = ["E", "F", "I", "B"]

[format]
# Используем двойные кавычки
quote-style = "double"

# Не отключаем магическую запятую
skip-magic-trailing-comma = false

# Используем пробелы для отступов
indent-style = "space"

# Автоматически детектируем конец строки
line-ending = "auto"