[project]
name = "lesson-01-uv-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veaceslavcalestru@gmail.com", email = "veaceslavcalestru@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy==1.23.2",
    "pandas==1.4.0",
    "scikit-learn==1.2.2",
]

[project.scripts]
lesson-01-uv-env = "lesson_01_uv_env:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
